name: 'CompatHelper'
description: 'Automatically update the [compat] entries for your Julia package''s dependencies'
author: 'Dilum Aluthge and contributors'

branding:
  icon: 'package'
  color: 'green'

inputs:
  ### Required inputs
  token:
    description: 'A GitHub token with write access on your repository'
    required: true
  ### Optional inputs
  cmd:
    description: 'The CompatHelper command to run. If you provide this input, you MUST also provide the `version` input.'
    required: false
    default: 'CompatHelper.main()'
  ssh:
    description: 'An SSH deploy key with write access on your repository'
    required: false
    default: ''
  version:
    description: 'Version of CompatHelper.jl to use'
    required: false
    default: '3'

runs:
  using: 'composite'
  steps:
    - run: |
        import Pkg
        ENV["JULIA_PKG_SERVER"] = ""
        Pkg.Registry.add("General")
      shell: julia --color=yes {0}
    - run: |
        import Pkg
        name = "CompatHelper"
        uuid = "aa819f21-2bde-4658-8897-bab36330d9b7"
        version = "${{ inputs.version }}"
        Pkg.add(; name, uuid, version)
      shell: julia --color=yes {0}
    - run: |
        import CompatHelper
        ${{ inputs.cmd }}
      shell: julia --color=yes {0}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        COMPATHELPER_PRIV: ${{ inputs.ssh }}
